version: '3'
services:
  esor-kali:
    image: esor-kali-vnc-ssh:latest
    tty: true
    container_name: esorone-kali-shh-vnc
    hostname: esor-kali
    ports:
      - "2222:22"
      - "5900:5900"
    networks:
      my-ntwk:
        ipv4_address: 172.17.0.4

